name: Build and Publish
on:
 workflow_dispatch:
 push:
    branches: v2

jobs:
  legacy_build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        mc_version: [
          '1.8.9',
        ]
    env:
      MC_VERSION: ${{ matrix.mc_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: python -u ./ci.py "$MC_VERSION" publishToLocalAndTest
  publish:
   needs: legacy_build
   runs-on: ubuntu-latest
   strategy:
     matrix:
       mc_version: [
           '1.8.9',
       ]
   env:
       MC_VERSION: ${{ matrix.mc_version }}
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v5
       with:
         python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
     - uses: actions/setup-java@v4
       with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '17'
     - run: python -u ./ci.py $MC_VERSION publish
       env:
         MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}
